//
//  SHA256Hash.swift
//
//  Created by tkgstrator on 2022/12/14
//  Copyright @2022 Magi, Corporation. All rights reserved.
//

import Foundation

public enum LocalizedType: String, CaseIterable, Identifiable, Codable {
	public var id: String { rawValue }
///  - 
case Widgets_StagesSeparator
/// %@%
case Widgets_VsPercent
/// %@p
case Widgets_VsTurfPoint
/// %@カウント
case Widgets_VsCount
/// + このそうびをマイコーデに追加
case MyOutfits_AddCurrentEquipments
/// -
case CoopEvent_Water_Levels
/// 100%踏破おめでとう！
case HeroRecord_NawabariMapSubComplete
/// : 
case Common_ColonRule
/// <em>ビッグラン</em>発生中！シャケから街を守れ！
case Footer_BigrunNowOpening
/// <em>ビッグラン</em>警報発令！シャケの接近に注意！
case Footer_BigrunAnnouncement
/// <em>ランクを4まで上げてザッカ屋でカタログを受け取ろう！</em>
case Catalog_Guide
/// About
case Custom_About
/// App Storeからダウンロード
case Landing_DlAppStore
/// Apple、Appleロゴ、App Storeは、Apple Inc.の商標です。Google Play および Google Play ロゴは Google LLC の商標です。
case Landing_Copyright
/// Clear!!
case CoopHistory_Clear
/// DRAW
case VSHistory_Draw
/// DRAW
case Widgets_VshistoryDraw
/// EX-WAVE
case CoopHistory_ExWave
/// Failure
case CoopHistory_Failure
/// Features
case Welcome_Features
/// GJ!
case CoopHistory_Gj
/// Google Playで手に入れよう
case Landing_DlGooglePlay
/// HH:mm
case Widgets_StagesTimeFormat
/// LOSE...
case VSHistory_Lose
/// LOSE...
case Widgets_VshistoryLose
/// Loading...
case MemoryPlayer_Loading
/// M/d HH:mm
case Widgets_StagesDatetimeFormat
/// My Nintendo Store
case Welcome_Store1
/// NG
case CoopHistory_Ng
/// NOW OPEN！
case StageSchedule_CoopCurrentPeriodStart
/// Nintendo Switch Online
case Landing_Nso
/// Nintendo Switch Onlineアプリを更新してください
case Widgets_ErrorsUpdateRequired
/// OFF
case MyOutfits_Off
/// ON
case MyOutfits_On
/// QRコードは、株式会社デンソーウェーブの登録商標です。
case Common_CopyrightQrCode
/// QRコードリーダー
case QRCodeReader_AppName
/// QRコードリーダー
case QRCodeReader_Title
/// TVモード/テーブルモード
case MyOutfits_TvTabletopMode
/// WIN!
case FesRecord_Win
/// WIN!
case VSHistory_Win
/// WIN!
case Widgets_VshistoryWin
/// Xパワー計測中
case VSHistory_Measurement
/// Xマッチ
case History_Xmatch
/// Xマッチ
case StageSchedule_Xmatch
/// Xマッチ
case VSHistory_Xmatch
/// Xマッチ
case Widgets_StagesXmatch
/// Xランキング
case XRanking_AppName
/// Xランキング
case XRanking_Title
/// Xランキングを見る
case History_ShowXranking
/// https://store-jp.nintendo.com/list/software/70010000046394.html
case Welcome_Link
/// yyyy M/d HH:mm
case Widgets_StagesYearDatetimeFormat
/// ※ 画像の加工や営利目的での利用、再配布はご遠慮ください。
case Challenge_TermOfUse
/// ※アプリをインストールしていない方は、このボタンを押しても開きません
case Landing_Caution
/// ※カッコ内の数字は自分で倒した数です
case CoopHistory_DefeatedEnemiesGuide
/// 「チャレンジャー・ロブ」としての次の目的地は『ハイカラ地方』に決めたよ～。<br />ってわけで、この旅を引き続き支援してくれるサポーターをパリッと募集するよ！<br />ハイカラ地方は、僕が旅を始める前に住んでた街もあるんだけど、いまもハイカラな香りたっぷりのツヤツヤアゲアゲな場所なんだよね～。<br />そういった思い出の場所を巡りながら、「過去の自分」も見つめ直して「いまの自分」を更にアゲ直したいんだよね！<br />この「二度アゲの旅」、ガチでホットっしょ？！ってことでヨロシク～！
case Challenge_Journey2Description
/// あすなろグリーンヒルズ
case HeroRecord_Site5
/// あなたのきろく
case FesRecord_YourRecord
/// あんしんライフファクトリー
case HeroRecord_Site2
/// あ！新しいアゲ油売ってる！！
case Challenge_Challenge26Description
/// いちにんまえ
case CoopGrade_Grade_02
/// いつものバイト
case CoopHistory_Regular
/// うめたてドリームランド
case HeroRecord_Site4
/// おうかん
case VSHistory_Xcrown
/// おうかん
case XRanking_Xcrown
/// おわる
case Common_End
/// おカネ
case GesoTown_Money
/// お礼のグラフィティをダウンロードできます
case Challenge_GuideGraffiti
/// かけだし
case CoopGrade_Grade_00
/// きろく
case Record_Title
/// きん
case VSHistory_AwardGold
/// ぎん
case VSHistory_AwardSilver
/// こうけん度 オープン
case FesRecord_ContributionRegular
/// こうけん度 チャレンジ
case FesRecord_ContributionChallenge
/// こうけん度 トリカラマッチ
case FesRecord_ContributionTricolor
/// ここだけの特別なギア販売中
case Carousel_Gesotown
/// ここだけの特別仕様！<br />ゲソタウンで限定ギアをチェック！
case Welcome_Feature4
/// ここの食堂はフライがイケてるバクアゲスポットなんだ～。
case Challenge_Challenge22Description
/// このQRコードはすでに無効です
case QRCodeReader_ErrorRewardExpiredDescription
/// このほうしゅうはすでに獲得済みです
case QRCodeReader_ErrorAlreadyGotDescription
/// このアンケートはゲーム内で投票するまで何度でも変更できます。<br />みんなの予定を見て、バンカラ街の広場にある投票所から投票しましょう。
case FesRecord_GuideVote
/// このウィジェットはスプラトゥーン3の連携サービスです。ゲームを遊ぶとデータが蓄積され利用できるようになります
case Widgets_ErrorsNoData
/// この商品は現在取り扱っておりません
case GesoTown_UnableToOrderMessage
/// これまでのフェス
case FesRecord_PastFestivals
/// これまでの読み取り履歴が表示されます
case QRCodeReader_NoData
/// こんなアガる要素しかない場所、アガり過ぎ注意報だよ～！ジュワワ～！！！
case Challenge_Challenge27Description
/// ご注文は、1回につき1コとなります
case GesoTown_Rule1
/// ご注文はいますぐ！
case GesoTown_OrderNow
/// しあわせリサーチラボ
case HeroRecord_Site6
/// しばらくお待ちください
case Error_MaintenanceTitle
/// じゅくれん
case CoopGrade_Grade_03
/// じゅくれん度
case Record_SkillLevel
/// じゅくれん度アップまで
case Record_NextSkillLevel
/// すでに注文済みのギアがあります
case GesoTown_Remind
/// すでに獲得しています
case QRCodeReader_ErrorAlreadyGotTitle
/// すべてのバッジを見る
case History_ShowAllBadges
/// すべて表示
case MyOutfits_All
/// すべて表示
case XRanking_All
/// そうびしていたギア
case VSHistory_EquippedGear
/// そうびしていたブキ
case VSHistory_EquippedWeapon
/// そうびなし
case HeroRecord_NoEquipments
/// そのつぎ
case StageSchedule_Future
/// その他
case History_Others
/// たおされたかいすう
case VSHistory_DeathCount
/// たおしたかいすう
case VSHistory_KillCount
/// たすけてもらったかいすう
case CoopHistory_RescuedCount
/// ただいまサーバーのメンテナンス中です。時間をおいて再度アクセスしてください。
case Error_MaintenanceDescription
/// ただいま販売中のギア
case GesoTown_Stock
/// たつじん
case CoopGrade_Grade_04
/// たつじん＋１
case CoopGrade_Grade_05
/// たつじん＋２
case CoopGrade_Grade_06
/// たつじん＋３
case CoopGrade_Grade_07
/// つぎ
case Catalog_NextBonus
/// つぎ
case StageSchedule_Next
/// でんせつ
case CoopGrade_Grade_08
/// ながいきヤングニュータウン
case HeroRecord_Site3
/// ぬりまといかくほ
case VSHistory_GotTricolorTreasure
/// はてな
case Common_GearPowerBlank
/// はんにんまえ
case CoopGrade_Grade_01
/// ひっぱって更新
case Common_PullToRefresh
/// ひとり旅に出たロブを支援して<br />特別な報酬をゲットしよう！
case Welcome_Feature3
/// ふだんとは違う<em>ギアパワー</em>がついた<br /><em>トクベツなギア</em>が手に入るショップ
case GesoTown_Description
/// へいきん
case FesRecord_Average
/// ほうしゅうの受け取りは<br />スプラトゥーン3のロビー端末を使ってね
case QRCodeReader_HowToGetReward
/// まもなくフェスマッチ開催
case Widgets_StagesFestMatchAnnounced
/// まもなく終了
case GesoTown_RemainAlmostFinished
/// みらいユートピアランド
case HeroRecord_Site1
/// みんなどこにする？<br />アンケート実施中
case FesRecord_PreVoteTitle
/// みんなアガッてる～？ 孤高のアゲアゲ旅人ロブだよ！<br />このプロジェクトは、僕のこれまでの歩みを振り返る旅、<br />その旅のクラウドファンディングなんだ～！
case Challenge_Story1
/// めちゃたそがれフォト
case Challenge_Challenge29Reward
/// めちゃ映えフォト
case Challenge_Challenge21Reward
/// めちゃ映えフォト
case Challenge_Challenge23Reward
/// めちゃ映えフォト
case Challenge_Challenge25Reward
/// めちゃ映えフォト
case Challenge_Challenge27Reward
/// もうすぐ開催
case FesRecord_ComingSoon
/// もうすぐ開催
case StageSchedule_FestivalAnnounced
/// もっともよく使ったブキ
case History_FrequentlyUsedWeapon
/// もっと見る
case History_ShowMore
/// よく使う
case Record_LatestUsed
/// るいけい
case FesRecord_Total
/// るいけいポイント
case CoopHistory_TotalPoint
/// アイコンのダウンロード
case Challenge_DownloadIcon
/// アタマ
case MyOutfits_Head
/// アタマを選ぶ
case MyOutfits_SelectHead
/// アップロードしたバトルメモリー
case MemoryPlayer_Uploaded
/// アップロードした人
case MemoryPlayer_UploadBy
/// アプリ
case Custom_Application
/// アプリのダウンロードはこちら
case Landing_Download
/// アプリを開く
case Landing_OpenApp
/// アラマキ砦
case CoopStage_Shakespiral
/// アラマキ砦
case CoopStage_Tutorial
/// アルバム
case PhotoAlbum_AppName
/// アルバム
case Widgets_AlbumTitle
/// アンケート実施中
case FesRecord_PreVoteButton
/// アートに触れるとハートの中心まで火が通るカンジするよね～！
case Challenge_Challenge21Description
/// イイ目をしたワカモノ求む！！
case HeroRecord_Recruitment
/// イエロー
case Challenge_Yellow
/// イカしたカタログ 配布中！
case Catalog_Welcome
/// イカリング2
case Custom_Ikaring2
/// イカリング３
case Common_Ikaring3
/// イカリング３で読み取ることのできる<br />QRコードではありません
case QRCodeReader_ErrorNotCompatibleDescription
/// イカリング３のQRコード読み取り機能がご利用いただけます。<br />QRコードの読み取りをご利用いただくと、どのQRコードを読み取ったかという情報が任天堂に送信され、アプリ内でQRコードの読み取り履歴を確認できるようになります。これにより、任天堂がお客様の位置情報を知ることができる場合があります。<br />以下のお客様の選択は保存されず、QRコードの読み取りをご利用いただくたびにお客様の同意（GDPR【第】6条【第】1項(a))が求められます。
case QRCodeReader_EuConfirmation
/// イカリング３のアルバムの画像を表示します。
case Widgets_AlbumDescription
/// イカリング３はスプラトゥーン3と連動するサービスです。<br />ここで紹介したもの以外にもさまざまな機能があります。
case Welcome_About
/// イカリング３を表示できません。しばらく時間をおいてから通信環境の良い場所で再度お試しください。<br />問題が解決しない場合は、ブラウザが最新版に更新されているか確認してください。<br />それでもこの画面が表示される場合は、ご利用の環境でイカリング３を利用できない可能性があります。
case Error_NotSupported
/// イクラ集め
case CoopHistory_RecruitTag2
/// イベント開催！
case StageSchedule_Eventmatch
/// ウィジェット
case Welcome_Widgets
/// ウデマエ
case History_Udemae
/// ウデマエアップ！
case VSHistory_UdemaeUp
/// ウデマエポイント
case VSHistory_UdemaePoint
/// ウロコ
case CoopHistory_Scale
/// エモート
case Catalog_Emote
/// エラー
case Error_Error
/// エラー
case QRCodeReader_ErrorNotCompatibleTitle
/// エラーが発生しました
case Error_ErrorOccurred
/// オオモノシャケ
case CoopHistory_Enemy
/// オカシラゲージ
case CoopHistory_SmellMeter
/// オカシラシャケ出現！
case CoopHistory_BossAvailable
/// オカシラシャケ撃破！
case CoopHistory_DefeatBoss
/// オキモノ
case Catalog_Figure
/// オフライン
case FriendList_Offline
/// オマツリのあかし
case VSHistory_FesWinProof
/// オルタナを100%踏破すると…？
case HeroRecord_NawabariMapSubInProgress
/// オルタナ探索率
case HeroRecord_NawabariMapProgress
/// オルタナ探索率100% 達成特典
case HeroRecord_NawabariMapCompleteReward
/// オレンジ
case Challenge_Orange
/// オレンジの空がオイリーだよね～。
case Challenge_Challenge210Description
/// オンライン
case FriendList_Online
/// オープン
case FesRecord_Regular
/// オープン
case StageSchedule_BankaraOpen
/// オープン！
case StageSchedule_Open
/// オープン！
case Widgets_StagesNowOpen
/// カタパッド
case CoopEnemy_SakelienCupTwins
/// カタログ
case Catalog_AppName
/// カタログ
case Catalog_Title
/// カタログポイント
case Catalog_Point
/// カタログレベル
case Catalog_Level
/// カタログレベルを上げて<br />ミステリーボックスをゲット！
case Catalog_BonusDescription
/// カメラでQRコードを読み取る
case QRCodeReader_ReadQrcodeByCamera
/// カメラオプション
case MyOutfits_CameraOption
/// カメラオプションを表示する
case MyOutfits_OpenCameraOption
/// カメラオプションを隠す
case MyOutfits_CloseCameraOption
/// カードスリーブ
case Catalog_CardSleeve
/// カードパック
case Catalog_CardPack
/// ガチアサリ
case Common_ClamBlitz
/// ガチエリア
case Common_SplatZones
/// ガチホコバトル
case Common_Rainmaker
/// ガチヤグラ
case Common_TowerControl
/// キケン度
case CoopHistory_DangerRatio
/// キミのおかげで、二度アゲの旅もカリッと終えられたよ！アリガト～！<br />お礼にコレ、アゲちゃうよ！<br />ロビー端末に送っておいたから受け取ってね～。
case Challenge_Journey2Gratitude
/// キャンセル
case Common_Cancel
/// キンウロコ
case CoopHistory_ScaleGold
/// キンシャケ
case CoopEnemy_SakelienGolden
/// キンシャケ探し
case CoopEvent_Goldie_Seeking
/// キンメダイ美術館
case Challenge_Challenge21Title
/// ギア
case MyOutfits_Gear
/// ギアを選択するとギアパワーの内訳が表示されます
case MyOutfits_GuideGearPowerButton
/// ギアパワー
case MyOutfits_GearPower
/// ギンウロコ
case CoopHistory_ScaleSilver
/// クツ
case MyOutfits_Shoes
/// クツを選ぶ
case MyOutfits_SelectShoes
/// クマサンポイントカード
case CoopHistory_KumaPointCard
/// クリアおめでとう！
case HeroRecord_NawabariMapSubCleared
/// クリアボーナス
case CoopHistory_Bonus
/// クレジット
case Custom_Credit
/// クレジット
case Settings_Credits
/// グラフィティのダウンロード
case Challenge_DownloadGraffiti
/// グラフィティ壁紙
case Challenge_Challenge28Reward
/// グリル
case CoopEnemy_Sakedozer
/// グリル発進
case CoopEvent_Griller
/// グリーン
case Challenge_Green
/// グループ
case XRanking_Region
/// グループ・アロメ
case XRanking_Atlantic
/// グループ・ヤコ
case XRanking_Pacific
/// ゲソタウン
case GesoTown_AppName
/// ゲソタウン
case GesoTown_Title
/// ゲソタウンに戻る
case GesoTown_BackToGesotown
/// ゲットした表彰
case VSHistory_GotAwards
/// ゲット！
case Catalog_Got
/// ゲーミングモード
case Custom_Gaming_Mode
/// コウモリ
case CoopEnemy_Sakerocket
/// コジャケ
case CoopEnemy_SakelienSmall
/// コピーしました
case MemoryPlayer_Copied
/// コンプリート特典
case Challenge_CompleteReward
/// コンプリート！
case Catalog_Complete
/// コンプリート！
case Challenge_Complete
/// コードを入力
case MemoryPlayer_Placeholder
/// サイズを選んでダウンロードしてください
case Challenge_SelectSize
/// サイズを選んでダウンロードしてください
case HeroRecord_Annotation
/// サブ
case Record_Sub
/// サブウェポン
case MyOutfits_Sub
/// サマリー
case History_Summary
/// サーモンラン
case Carousel_CoopHistory
/// サーモンラン
case CoopHistory_Title
/// サーモンラン
case StageSchedule_Coop
/// サーモンラン
case Widgets_StagesCoop
/// ザッカ屋
case Catalog_Signboard
/// ザトウマーケット
case Challenge_Challenge26Title
/// シェア
case Common_Share
/// シェケナダム
case Challenge_Challenge210Title
/// シェケナダム
case CoopStage_Shakeup
/// シェルター
case WeaponTypeName_Shelter
/// シャケ
case CoopEnemy_SakelienStandard
/// シャケコプター
case CoopEnemy_SakeCopter
/// シューター
case WeaponTypeName_Shooter
/// シーズン
case History_Season
/// ジェットコースターに乗った後って、ナゼか身軽に感じるんだよね～。
case Challenge_Challenge28Description
/// ジャイロ操作
case MyOutfits_GyroControl
/// ジャイロ操作OFFの時は無効になります
case MyOutfits_RHorizontalUnavailable
/// ジャイロ操作ONの時は無効になります
case MyOutfits_RVerticalUnavailable
/// ジャイロ操作感度
case MyOutfits_Gyro
/// スケジュール
case StageSchedule_Title
/// スケジュールがありません
case Widgets_StagesNoData
/// スケジュールを見る
case CoopHistory_SeeSchedule
/// スケジュールサーバーから過去のスケジュールを取得します
case Custom_Schedule_Sync_Txt
/// スケジュール同期
case Custom_Schedule_Sync
/// スタッフ募集！
case CoopHistory_Recruit
/// ステッカー
case Catalog_Sticker
/// ステージ
case Record_StageRecordAppName
/// ステージのきろく
case Record_StageRecord
/// ステージスケジュール
case Widgets_StagesTitle
/// ストリンガー
case WeaponTypeName_Stringer
/// スナップ写真
case HeroRecord_AreaMemorialPhoto
/// スナップ写真を見る
case HeroRecord_SeePhotograph
/// スピナー
case WeaponTypeName_Spinner
/// スプラトゥーン3
case Landing_Splatoon3
/// スプラトゥーン3
case Welcome_Splatoon3
/// スプラトゥーン3でイカした写真を<br />撮影するとココに表示されるぞ！
case Widgets_AlbumNoPhoto
/// スプラトゥーン3のステージスケジュールと現在のそうびを表示します。
case Widgets_StagesDescriptionAndroid
/// スプラトゥーン3のステージスケジュールを表示します。
case Widgets_StagesDescription
/// スプラトゥーン3のバトルのきろくを表示します。
case Widgets_VshistoryDescription
/// スプラトゥーン3の現在のそうびを表示します。
case Widgets_EquipmentsDescription
/// スペシャル
case Record_Special
/// スペシャルウェポン
case MyOutfits_Special
/// スペシャルウェポンはつどうかいすう
case VSHistory_SpCount
/// スマートフォンアプリ『Nintendo Switch Online』にログインしてください
case Widgets_ErrorsNotLoggedIn
/// スマートフォンアプリ『Nintendo Switch Online』を開きます
case Landing_Title
/// スメーシーワールド
case Challenge_Challenge28Title
/// スメーシーワールド
case CoopStage_Carousel
/// スロッシャー
case WeaponTypeName_Slosher
/// ソースコード
case Custom_Source_Code
/// タマヒロイ
case CoopEnemy_SakeFlyBagman
/// タワー
case CoopEnemy_SakelienTower
/// ターコイズ
case Challenge_Turquoise
/// ダイバー
case CoopEnemy_SakeDolphin
/// ダウンロード
case Common_Download
/// ダウンロードしたバトルメモリーは<br />スプラトゥーン3のロビー端末のメモリープレーヤーで再生することができます
case MemoryPlayer_Guide
/// ダウンロードコード
case MemoryPlayer_ReplayCode
/// ダウンロード予約しました
case MemoryPlayer_ReservedDownload
/// ダウンロード予約に失敗しました
case MemoryPlayer_FailedDownload
/// ダークモード
case Custom_Dark_Mode
/// チャレンジ
case FesRecord_Challenge
/// チャレンジ
case StageSchedule_BankaraOpenChallenge
/// チャレンジャー
case Challenge_Challenger
/// チャージャー
case WeaponTypeName_Charger
/// チャージ速度
case ParamName_Charge
/// チョウザメ造船
case Challenge_Challenge24Title
/// チョーシ
case Record_Vibes
/// テスト
case Custom_Role_Tester
/// テッキュウ
case CoopEnemy_SakeArtillery
/// テッパン
case CoopEnemy_SakelienShield
/// デバッグ
case Custom_Role_Debuger
/// データが見つかりません
case MemoryPlayer_ReplayNotAvailable
/// データベースのバックアップを出力します。
case Custom_Backup_Txt
/// データ管理
case Custom_Data_Management
/// トップ 500
case XRanking_Top500
/// トッププレイヤー
case XRanking_TopPlayers
/// トライかいすう
case VSHistory_TryCount
/// トリカラアタック
case Common_Tricolor
/// トリカラマッチ
case Common_TricolorMatch
/// ドウウロコ
case CoopHistory_ScaleBronze
/// ドスコイ
case CoopEnemy_SakelienLarge
/// ドスコイ大量発生
case CoopEvent_Cohock_Charge
/// ドリンクチケット
case Catalog_DrinkTicket
/// ドロシャケ
case CoopEnemy_SakeBigMouth
/// ドロシャケ
case CoopEnemy_SakeBigMouthGold
/// ドロシャケ噴出
case CoopEvent_Mudmouth
/// ナベブタ
case CoopEnemy_SakeSaucer
/// ナワバリバトル
case Common_TurfWar
/// ニンテンドーアカウントとの連携を解除します
case Custom_Sign_Out_Txt
/// ノックアウト！
case VSHistory_Knockout
/// ノックアウト！
case Widgets_VsKnockout
/// ノーマル
case MyOutfits_Normal
/// ハイカラ地方にもサクサク稼げるバイトがあるんだね～！って、ココどこ～？
case Challenge_Challenge29Description
/// ハコビヤ襲来
case CoopEvent_The_Mothership
/// ハシラ
case CoopEnemy_SakePillar
/// バイトスコア
case CoopHistory_Score
/// バイトツナギ イエロー
case SkinName_COP003
/// バイトツナギ オレンジ
case SkinName_COP001
/// バイトツナギ グリーン
case SkinName_COP002
/// バイトツナギ ピンク
case SkinName_COP004
/// バイトツナギ ブラック
case SkinName_COP006
/// バイトツナギ ブルー
case SkinName_COP005
/// バイトツナギ ホワイト
case SkinName_COP007
/// バイトヒストリー
case CoopHistory_History
/// バイトヒストリーがありません
case CoopHistory_NoData
/// バイトヒストリーを表示できません
case CoopHistory_NotAvailable
/// バイトヒストリー一覧に戻る
case CoopHistory_GoToStats
/// バイト中
case FriendList_InCoopGame
/// バイト回数
case CoopHistory_PlayCount
/// バクダン
case CoopEnemy_SakelienBomber
/// バックアップ
case Custom_Backup
/// バッジ
case History_Badge
/// バトル
case VSHistory_Title
/// バトルでカタログポイントを貯めて<br />アイテムをゲットしよう！
case Catalog_WelcomeDescription
/// バトルのきろく
case Widgets_VshistoryTitle
/// バトルのきろくがありません
case VSHistory_NoData
/// バトルのきろくがありません
case Widgets_VsNoData
/// バトルのきろくに戻る
case VSHistory_GoToStats
/// バトルのきろくを表示できません
case VSHistory_NotAvailable
/// バトルの戦績やスケジュール
case Welcome_Feature1Alt
/// バトルの戦績やスケジュールをチェックして<br />ライバルに差をつけろ！
case Welcome_Feature1
/// バトルメモリーのダウンロード
case MemoryPlayer_Download
/// バトル戦績
case Carousel_VsHistory
/// バンカラマッチ
case StageSchedule_Bankara
/// バンカラマッチ
case VSHistory_Bankara
/// バンカラマッチ
case Widgets_StagesBankara
/// バンカラマッチ オープン
case VSHistory_BankaraOpen
/// バンカラマッチ チャレンジ
case VSHistory_BankaraChallenge
/// バージョン
case Custom_Version
/// パスワードつき
case FriendList_IsLocked
/// パープル
case Challenge_Purple
/// ヒストリー
case History_AppName
/// ヒストリー
case History_Title
/// ヒラメが丘団地
case Challenge_Challenge25Title
/// ヒーローモード
case HeroRecord_AppName
/// ヒーローモード をはじめて冒険をすすめよう
case HeroRecord_RecruitmentSub
/// ヒーローモード クリア特典
case HeroRecord_ClearReward
/// ヒーローモードのきろく
case HeroRecord_Title
/// ビッグラン
case Common_CoopBigRun
/// ビッグラン
case CoopHistory_Bigrun
/// ビッグランから街を守れ！
case Carousel_BigrunOpening
/// ビッグラン接近中！
case StageSchedule_NoticeBigrun
/// ビッグラン発生中！
case StageSchedule_OpenBigrun
/// ビッグラン結果発表！
case Carousel_BigrunResult
/// ビッグラン開催中！ポイント<em>1.2倍</em>！
case Catalog_BigrunBonus
/// ピックアップ
case GesoTown_Featured
/// ファイルアプリからリストアするファイルを選択してください。
case Custom_Restore_Txt
/// ファッションリーダーたちに朗報！<br />いつでもマイコーデを編集できるぞ！
case Welcome_Feature2
/// フェス
case FesRecord_AppName
/// フェス100ケツ
case FesRecord_FestRanking
/// フェス100ケツを見る
case FesRecord_SeeFestRanking
/// フェスのきろく
case FesRecord_Title
/// フェスのきろくを見る
case StageSchedule_SeeFestivalRecord
/// フェスマッチ
case StageSchedule_Festival
/// フェスマッチ
case VSHistory_Festival
/// フェスマッチ開催中！
case StageSchedule_NowClosed
/// フェスマッチ開催中！
case Widgets_StagesFestMatch
/// フェスマッチ（オープン）
case VSHistory_FesOpen
/// フェスマッチ（チャレンジ）
case VSHistory_FesChallenge
/// フェス結果発表！！
case Carousel_FestResult
/// フェス開催中！ポイント<em>1.2倍</em>！
case Catalog_FesBonus
/// フェス開催！！
case Carousel_FestOpening
/// フォトアルバム
case Carousel_PhotoAlbum
/// フォトアルバム
case PhotoAlbum_Title
/// フク
case MyOutfits_Cloth
/// フクを選ぶ
case MyOutfits_SelectCloth
/// フデ
case WeaponTypeName_Brush
/// フレッシュカードパック
case Catalog_CardPackFresh
/// フレンドのプレイ状況がここに表示されます
case FriendList_NoFriends
/// フレンドの参加チームを見る
case FesRecord_SeeAllVotes
/// フレンドの参加予定を見ることができます。<br />みんなでチームを組んで参加しよう！
case FesRecord_PreVoteGuide
/// フレンドの投票状況
case FesRecord_VotingStatus
/// フレンドリスト
case FriendList_AppName
/// フレンドリスト
case FriendList_Title
/// フードチケット
case Catalog_FoodTicket
/// ブキ
case MyOutfits_Weapon
/// ブキ
case Record_WeaponRecordAppName
/// ブキのきろく
case Record_WeaponRecord
/// ブキを選ぶ
case MyOutfits_SelectWeapon
/// ブキを選ぶ
case XRanking_SelectWeapon
/// ブキトップ プレイヤー
case XRanking_WeaponTop
/// ブキトップ プレイヤー
case XRanking_WeaponTopSingular
/// ブキトップを見る
case XRanking_SeeWeaponTop
/// ブキヒストリー
case History_Weapon
/// ブキ使用率
case History_WeaponUsage
/// ブラスター
case WeaponTypeName_Blaster
/// ブラック
case Challenge_Black
/// ブランド
case MyOutfits_Brand
/// ブルー
case Challenge_Blue
/// プライバシーポリシー
case Custom_Privacy_Policy
/// プライベート
case CoopHistory_Private
/// プライベートマッチ
case StageSchedule_Private
/// プライベートマッチ
case VSHistory_Private
/// プレート
case Catalog_NamePlateBg
/// ヘビ
case CoopEnemy_SakelienSnake
/// ホラガイ獲得個数
case FesRecord_GotHoragai
/// ホラガイ獲得率
case FesRecord_Horagai
/// ホワイト
case Challenge_White
/// ホーム
case Common_Home
/// ホームに戻る
case Error_BackToHome
/// ボイスチャットかのう
case FriendList_VoiceChatEnabled
/// ボス
case HeroRecord_BossStage
/// ボーナス！
case Catalog_BonusTitle
/// ポイント送信中...
case Challenge_SendingPoint
/// マイコーデ
case Carousel_Myoutfits
/// マイコーデ
case MyOutfits_AppName
/// マイコーデ
case MyOutfits_Title
/// マイコーデは5つまで作成することができます
case MyOutfits_GuideLimitation
/// マイコーデをつくってみよう
case MyOutfits_Guide
/// マイコーデをつくる
case MyOutfits_Add
/// マサバ海峡大橋
case Challenge_Challenge23Title
/// マニューバー
case WeaponTypeName_Maneuver
/// マヒマヒリゾート＆スパ
case Challenge_Challenge27Title
/// ミステリーボックス
case Catalog_MysteryBox
/// ムニ・エール海洋発電所
case CoopStage_Shakedent
/// メイン
case Record_Main
/// メインウェポン
case MyOutfits_Main
/// メモリープレーヤー
case Carousel_MemoryPlayer
/// メモリープレーヤー
case MemoryPlayer_AppName
/// メモリープレーヤー
case MemoryPlayer_Title
/// モグラ
case CoopEnemy_Sakediver
/// ユーザーデータ
case Custom_User_Data
/// ヨコヅナ
case CoopEnemy_SakelienGiant
/// ラッシュ
case CoopEvent_Rush
/// ランキングを見る
case XRanking_SeeRanking
/// ランク
case History_Rank
/// ランダム
case StageSchedule_SuppliedWeaponRandom
/// リザルト件数
case Custom_Results_Count
/// リストア
case Custom_Restore
/// リバース
case MyOutfits_Reverse
/// リワードのアイコンをダウンロードできます
case Challenge_GuideRewardIcon
/// リワードのスリーブをロビー端末から受け取れます
case Challenge_GuideRewardSleeve
/// リワードの二つ名をロビー端末から受け取れます
case Challenge_GuideRewardByName
/// リワードの画像をダウンロードできます
case Challenge_GuideRewardImage
/// リーグマッチ
case StageSchedule_League
/// リーグマッチ
case Widgets_StagesLeague
/// ルールごとの勝率
case StageSchedule_WinRateByRules
/// レギュラーマッチ
case StageSchedule_Regular
/// レギュラーマッチ
case VSHistory_Regular
/// レギュラーマッチ
case Widgets_StagesRegular
/// レッド
case Challenge_Red
/// レビューを書く
case Custom_Write_Review
/// レベル10ごとにミステリーボックスをゲットできます
case Catalog_BonusGuide
/// ログアウト
case Custom_Sign_Out
/// ログイン
case Custom_Sign_In
/// ログ送信
case Custom_Log
/// ロブ
case Challenge_Rob
/// ロブから支援者のみなさまへ
case Challenge_DearAllOfYou
/// ロブのアゲアゲ旅
case Challenge_RobJourney
/// ロブイチ
case Challenge_AppName
/// ロブイチ
case Challenge_Title
/// ロード中
case Common_NowLoading
/// ロード中
case Widgets_Loading
/// ローラー
case WeaponTypeName_Roller
/// ワイパー
case WeaponTypeName_Saber
/// 一致するギアがありません
case MyOutfits_NoGears
/// 一致するブキがありません
case MyOutfits_NoWeapons
/// 並び替え
case Record_Sort
/// 二つ名
case Catalog_Byname
/// 二つ名
case Challenge_Challenge210Reward
/// 人数が少ない時間が続いたため、負けとしてカウントされませんでした
case VSHistory_AnnotationExemption
/// 今まで塗った面積
case History_TotalTurfPoint
/// 今月のギア
case CoopHistory_MonthlyReward
/// 他にも便利な機能がたくさん！
case Welcome_OtherFeatures
/// 保存
case MyOutfits_Save
/// 保存した画像から読み取る
case QRCodeReader_ReadQrcodeByFile
/// 保存に失敗しました
case MyOutfits_ErrorSave
/// 保存先の選択
case MyOutfits_SelectSlot
/// 倒したオオモノシャケ
case CoopHistory_DefeatedEnemies
/// 倒したオカシラシャケ
case CoopHistory_DefeatBossCount
/// 倒した！
case CoopHistory_Defeated
/// 倒せなかった...
case CoopHistory_NotDefeated
/// 僕がこれまでに立ち寄ったアツアツでアゲアゲなアツアゲスポットを自転車で一周するよ！<br />そこで自分の「今」の立ち位置をジュワ～ッと見つめなおしてアゲなおそうと思うんだよね～。<br />そんな旅の中で得た「気づき」「発見」「Notice」を支援してくれるみんなにもシェアしたいと思ってるんだ～。<br />これってテンションフライハイっしょ？！
case Challenge_Story2
/// 再読みこみ
case Error_Reload
/// 再読みこみ
case FriendList_Reload
/// 写真は20枚までアップロードできます<br />保存期間は3ヶ月です
case PhotoAlbum_Annotation
/// 出現したオカシラシャケ
case CoopHistory_AvailableBoss
/// 出現数
case CoopHistory_Available
/// 初心者でも安心！元気で明るい方大歓迎！<br />アットホームな職場でアルバイトをしてみませんか？
case CoopHistory_RecruitDescription
/// 前のギア
case GesoTown_Previous
/// 前のバイト
case CoopHistory_Previous
/// 前のバトル
case VSHistory_PreviousBattle
/// 前へ
case HeroRecord_Prev
/// 前シーズンのヒストリーはこちら！
case Carousel_StatsLatestSeason
/// 助けた回数
case CoopHistory_RescueCount
/// 勝利数
case Record_WinCount
/// 勝敗数について
case VSHistory_WinMeterGuide
/// 募集中
case FriendList_Recruiting
/// 参加予定
case FesRecord_Vote
/// 参加予定のフレンドはチームが変わることがあります
case FesRecord_GuideWillParticipates
/// 受付できません
case GesoTown_UnableToOrder
/// 商品は4時間ごとに入れ替わります
case GesoTown_StockGuide
/// 回答済み
case FesRecord_Voted
/// 圧縮(ZIP)
case Custom_Backup_Compress
/// 在庫確認中...
case GesoTown_Pending
/// 塗りまくって貯めたポイントでロブの旅を応援しよう！<br />旅の思い出も手に入るかも？！
case Challenge_HowToPlay
/// 塗りポイント
case Record_TurfPoint
/// 塗り進み速度
case ParamName_PaintSpeed
/// 壁紙のダウンロード
case Challenge_DownloadWallpaper
/// 夕飯時にフライの香りがすると、すぐ家に帰りたくなるよね～。
case Challenge_Challenge25Description
/// 外観
case Custom_Appearances
/// 守備
case FesRecord_Defense
/// 守備
case StageSchedule_FestivalDefense
/// 守備
case VSHistory_Defense
/// 射程
case ParamName_Range
/// 履歴
case QRCodeReader_History
/// 巨大タツマキ
case CoopEvent_Giant
/// 干潮
case CoopHistory_WaveLevel0
/// 平均クリアWAVE数
case CoopHistory_AverageClearWaves
/// 引き換えできます
case Catalog_Available
/// 得票率
case FesRecord_VoteRatio
/// 投票済み
case FesRecord_VotedInGame
/// 拾ったステッカー
case Challenge_Challenge22Reward
/// 拾ったステッカー
case Challenge_Challenge24Reward
/// 拾ったステッカー
case Challenge_Challenge26Reward
/// 挑戦中
case VSHistory_InChallenge
/// 挑戦中止
case VSHistory_UdemaeReset
/// 探索率
case HeroRecord_SearchRatio
/// 推定順位
case History_EstimatedRanking
/// 携帯モード
case MyOutfits_HandheldMode
/// 支援する
case Challenge_Support
/// 支援するチャレンジを選ぶ
case Challenge_ChooseChallenge
/// 支援に使える塗りポイント
case Challenge_CurrentPoint
/// 支援に必要な塗りポイント
case Challenge_PointForSupport
/// 支援済み
case Challenge_Supported
/// 支援者求む！
case Carousel_Robichi
/// 支援者求ム！
case Challenge_LookingForSupporters
/// 支給ブキ
case CoopHistory_SupplyWeapon
/// 支給ブキ
case StageSchedule_SuppliedWeapons
/// 支給ブキ
case Widgets_StagesSuppliedWeapons
/// 攻撃
case FesRecord_Attack
/// 攻撃
case StageSchedule_FestivalAttack
/// 攻撃
case VSHistory_Attack
/// 攻撃力
case ParamName_Power
/// 新たなヒーローの物語
case Carousel_HeroRecord
/// 旅するなかでバクアゲ～！と思った風景写真や思い出の品は支援してくれたみんなにも送るからね～。<br />『みんなも一緒に旅する仲間っしょ！』っていう、一体感とかグルーヴを生み出せたらもっとアガるよね～！<br />そんなこんなでこれからアゲアゲの旅をサクッと始めちゃうんでヨロシク～！
case Challenge_Story3
/// 旅の途中<br />～どの道を塗るかより、塗った道をどう進むか～
case Challenge_Journey2Title
/// 旅の途中でテンションバクアゲ～！なグラフィティ見つけたから送るね～
case Challenge_AboutGraffiti
/// 昇格戦
case VSHistory_Promo
/// 普通
case CoopHistory_WaveLevel1
/// 最後に遊んだ
case Record_LatestPlayed
/// 最新の50件を表示しています<br />保存期間は30日です
case MemoryPlayer_Notice
/// 最新のバイトへ
case CoopHistory_Latest
/// 最新のバトル
case VSHistory_LatestBattle
/// 最近
case VSHistory_LatestTab
/// 最近 3ヶ月
case History_Latest
/// 最近の50戦
case VSHistory_Latest
/// 最近ゲットしたバッジ
case History_LatestBadge
/// 最高Xランキング・最高Xパワー
case History_HighestXranking
/// 最高きろく
case CoopHistory_HighestScore
/// 最高ウデマエ
case History_HighestUdemae
/// 最高フェスパワー
case FesRecord_HighestFestPower
/// 月間
case History_Monthly
/// 有効
case Custom_Valid
/// 期間限定
case CoopHistory_Limited
/// 期間限定バイト開催中！
case StageSchedule_OpenLimited
/// 期間限定バイト開催予告！
case StageSchedule_NoticeLimited
/// 期限切れ
case GesoTown_NotAvailable
/// 未定
case FesRecord_Undecided
/// 未定のフレンド
case FesRecord_NotVoted
/// 未所持のブキ
case Record_UnusedWeapons
/// 本日のピックアップ
case GesoTown_Feature
/// 本気のヤツらのためのイカしたサービス
case Welcome_Service
/// 権利表記
case Settings_Acknowledgements
/// 橋の上は風が強くてコロモがめっちゃ飛ばされるんだよね！
case Challenge_Challenge23Description
/// 機動性
case ParamName_Mobility
/// 次のギア
case GesoTown_Next
/// 次のバイト
case CoopHistory_Next
/// 次のバトル
case VSHistory_NextBattle
/// 次のピックアップ
case GesoTown_NextFeature
/// 次へ
case HeroRecord_Next
/// 正常に試合が終了しませんでした
case VSHistory_AnnotationPenalty
/// 決定
case Common_Decide
/// 決定
case MyOutfits_SubmitGear
/// 決定
case MyOutfits_SubmitWeapon
/// 注文する
case GesoTown_Order
/// 注文済み
case GesoTown_Ordered
/// 注文済みのギアは、広場のスパイキーから購入できます
case GesoTown_Rule2
/// 注文済みのギアはキャンセルされます
case GesoTown_RemindCaution
/// 海女美術大学
case Challenge_Challenge22Title
/// 清算
case VSHistory_Cleaning
/// 満潮
case CoopHistory_WaveLevel2
/// 溶接の音とアゲる音って似てるから、テンションがバチバチアガっちゃうよ！
case Challenge_Challenge24Description
/// 無効
case Custom_Invalid
/// 無効試合になりました
case VSHistory_AnnotationNocontest
/// 無色
case Challenge_Transparent
/// 爆発力
case ParamName_Explosion
/// 特典をゲット
case HeroRecord_GetReward
/// 特定の場所にあるQRコードを読み取ると<br />特別なほうしゅうをゲットできます
case QRCodeReader_Guide
/// 特製壁紙
case HeroRecord_Wallpaper
/// 獲得ポイント
case CoopHistory_JobPoint
/// 現在のそうび
case MyOutfits_CurrentEquipments
/// 現在のそうび
case Widgets_EquipmentsTitle
/// 現在のそうびは最後に対戦を行った内容を表示しています
case MyOutfits_CurrentEquipmentsGuide
/// 現在のポイント
case CoopHistory_RegularPoint
/// 現在利用できません
case Widgets_ErrorsOutOfService
/// 現在利用できません。しばらくお待ちください
case Error_CurrentlyNotAvailable
/// 簡単
case CoopHistory_RecruitTag1
/// 結果を集計中です
case FesRecord_WaitingForResult
/// 絞り込む
case MyOutfits_Filter
/// 総勝利数
case History_TotalWin
/// 翻訳
case Custom_Role_Translator
/// 耐久力
case ParamName_Defence
/// 色を選んでダウンロードしてください
case Challenge_SelectColor
/// 表示するモード
case Widgets_StagesSettingsMode
/// 表示を減らす
case History_ShowLess
/// 言語
case Custom_Languages
/// 計測中
case XRanking_Measurement
/// 設定
case Settings_AppName
/// 設定
case Settings_Title
/// 許可
case QRCodeReader_ConfirmationAllow
/// 許可しない
case QRCodeReader_ConfirmationDeny
/// 評価レート
case CoopHistory_JobRatio
/// 試合中
case FriendList_InVsGame
/// 読みこみに失敗しました
case Error_ErrorReopen
/// 読みこみに失敗しました。<br />通信環境のよいところで再度お試しください。
case Error_NetworkNotAvailable
/// 購入サイトへ
case Welcome_Store
/// 購入前に新しく注文すると、注文済みのギアはキャンセルされます
case GesoTown_Rule3
/// 購入後、新しい注文が可能になります
case GesoTown_Rule4
/// 軽さ
case ParamName_Weight
/// 追加ギアパワー1個は、基本ギアパワー0.3個分の効果です
case MyOutfits_GearPowerAnnotation
/// 送信
case MemoryPlayer_Send
/// 連射力
case ParamName_Blaze
/// 遊んでないステージ
case Record_UnplayedStages
/// 過去のランキング
case XRanking_PastRankings
/// 達成しました
case Challenge_Clear
/// 選択
case PhotoAlbum_Select
/// 選択中のギア
case MyOutfits_CurrentGear
/// 選択中のブキ
case MyOutfits_CurrentWeapon
/// 閉じる
case Common_Close
/// 開催中！
case StageSchedule_FestivalHolding
/// 開催中！！
case FesRecord_OnGoing
/// 開催中！！
case XRanking_Open
/// 開発
case Custom_Role_Developer
/// 開発者にログを送信します
case Custom_Log_Txt
/// 閲覧できるバイトヒストリーは、最新の50戦までです。
case CoopHistory_NotAvailableDescription
/// 閲覧できるバトルのきろくは、モードごとに最新の50戦までです。
case VSHistory_NotAvailableDescription
/// 集めたイクラ
case CoopHistory_DeliverCount
/// 集めた金イクラ
case CoopHistory_GoldenDeliverCount
/// 難破船ドン・ブラコ
case Challenge_Challenge29Title
/// 難破船ドン・ブラコ
case CoopStage_Shakeship
/// 霧
case CoopEvent_Fog
/// 非圧縮(JSON)
case Custom_Backup_No_Compress
/// １号
case HeroRecord_Agent1
/// １０倍マッチ
case VSHistory_10x
/// １００倍マッチ
case VSHistory_100x
/// ２号
case HeroRecord_Agent2
/// ３３３倍マッチ
case VSHistory_333x
/// ？？？
case CoopStage_Unknown
/// ～イカした制服でイクラ集め～
case CoopHistory_RecruitTitle
